In [8]:
import numpy as np

# Format the output with 2 decimal places.
np.set_printoptions(precision=2, suppress=True)

# 1. Give a matrix
A = np.array([[4,11,14],
              [8,7,-2]])
print("Original Matrix A:\n", A)

# 2. SVD
U, s, Vt = np.linalg.svd(A, full_matrices=False)

print("\nU:\n", U)   # left singular vectors 
print("\ns:\n", s)     # singular values  (1D array)
print("\nVt:\n", Vt)   # right singular vectors  (transposed)

# 3. reconstruct origional matrix
S = np.diag(s)  # transform singular values from 1D array into diagonal matrix
A_reconstructed = U @ S @ Vt

print("\nReconstructed A (using all singular values):\n", A_reconstructed)
print("\nReconstruction error):", np.round(np.linalg.norm(A - A_reconstructed),2))

Original Matrix A:
 [[ 4 11 14]
 [ 8  7 -2]]

U:
 [[-0.95 -0.32]
 [-0.32  0.95]]

s:
 [18.97  9.49]

Vt:
 [[-0.33 -0.67 -0.67]
 [ 0.67  0.33 -0.67]]

Reconstructed A (using all singular values):
 [[ 4. 11. 14.]
 [ 8.  7. -2.]]

Reconstruction error): 0.0


In [7]:
# 4. Low-rank approximation via truncated singular values
k = 1  # Only use the first singular values
U_k = U[:, :k]
S_k = np.diag(s[:k])
Vt_k = Vt[:k, :]
A_approx = U_k @ S_k @ Vt_k

print("\nU_k:\n", U_k)   
print("\nS_k:\n", S_k)
print("\nVt_k:\n", Vt_k)

print(f"\nLow-rank approximation with k={k}:\n", A_approx)
print("\nApproximation error:", np.round(np.linalg.norm(A - A_approx),2))


U_k:
 [[-0.95]
 [-0.32]]

S_k:
 [[18.97]]

Vt_k:
 [[-0.33 -0.67 -0.67]]

Low-rank approximation with k=1:
 [[ 6. 12. 12.]
 [ 2.  4.  4.]]

Approximation error: 9.49


In [4]:
import numpy as np

# Format the output with 2 decimal places.
np.set_printoptions(precision=2, suppress=True)

# 1. Give a matrix
A = np.array([[2,1],[1,2]])
print("Original Matrix A:\n", A)

# 2. SVD
U, s, Vt = np.linalg.svd(A, full_matrices=False)

print("\nU:\n", U)   # left singular vectors 
print("\ns:\n", s)     # singular values  (1D array)
print("\nVt:\n", Vt)   # right singular vectors  (transposed)

# 3. reconstruct origional matrix
S = np.diag(s)  # transform singular values from 1D array into diagonal matrix
A_reconstructed = U @ S @ Vt

print("\nReconstructed A (using all singular values):\n", A_reconstructed)
print("\nReconstruction error):", np.round(np.linalg.norm(A - A_reconstructed),2))

Original Matrix A:
 [[2 1]
 [1 2]]

U:
 [[-0.71 -0.71]
 [-0.71  0.71]]

s:
 [3. 1.]

Vt:
 [[-0.71 -0.71]
 [-0.71  0.71]]

Reconstructed A (using all singular values):
 [[2. 1.]
 [1. 2.]]

Reconstruction error): 0.0


In [5]:
import numpy as np

# Format the output with 2 decimal places.
np.set_printoptions(precision=2, suppress=True)

# 1. Give a matrix
A = np.array([[2,1,4],[1,2,9]])
print("Original Matrix A:\n", A)

# 2. SVD
U, s, Vt = np.linalg.svd(A, full_matrices=False)

print("\nU:\n", U)   # left singular vectors 
print("\ns:\n", s)     # singular values  (1D array)
print("\nVt:\n", Vt)   # right singular vectors  (transposed)

# 3. reconstruct origional matrix
S = np.diag(s)  # transform singular values from 1D array into diagonal matrix
A_reconstructed = U @ S @ Vt

print("\nReconstructed A (using all singular values):\n", A_reconstructed)
print("\nReconstruction error):", np.round(np.linalg.norm(A - A_reconstructed),2))

Original Matrix A:
 [[2 1 4]
 [1 2 9]]

U:
 [[-0.43 -0.9 ]
 [-0.9   0.43]]

s:
 [10.25  1.4 ]

Vt:
 [[-0.17 -0.22 -0.96]
 [-0.98 -0.03  0.18]]

Reconstructed A (using all singular values):
 [[2. 1. 4.]
 [1. 2. 9.]]

Reconstruction error): 0.0
